// apps/site/src/routes/(dashboard)/bills.tsx
import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/(dashboard)/bills")({
  component: Page,
});

function Page() {
  return (
    <>
      <header>
        <h1 id="a11ty-headline" className="text-4xl font-bold text-grey-900">
          Recurring Bills
        </h1>
      </header>
      <div className="p-8">
        <p>Recurring bills content coming soon...</p>
      </div>
    </>
  );
}

// apps/site/src/routes/(dashboard)/bills/+page.svelte
<script lang="ts">
</script>

<svelte:head>
	<title>Recurring Bills - Pennywise</title>
	<meta name="description" content="Track and manage your recurring bills" />
	<meta name="robots" content="noindex, nofollow" />
</svelte:head>

<header>
	<h1 id="a11ty-headline" class="text-grey-900 text-4xl font-bold">Recurring Bills</h1>
</header>

<div class="p-8">
	<p>Recurring bills content coming soon...</p>
</div>
