// apps/site/src/routes/(dashboard)/+page.svelte
<script lang="ts">
</script>

<svelte:head>
	<title>Dashboard - Pennywise</title>
	<meta
		name="description"
		content="Pennywise helps you track spending, stick to budgets, and reach savings goals faster. Beautiful insights, powerful features, bank-level security. Start your journey to financial wellness today."
	/>
	<meta
		name="keywords"
		content="personal finance, personal finance software, budget tracker, budget planner, expense tracking, track expenses, savings goals, financial planning, money management, budget app, spending tracker, financial wellness"
	/>
	<meta name="robots" content="noindex, nofollow" />

	<meta property="og:type" content="website" />
	<meta property="og:url" content="https://pennywise.com" />
	<meta property="og:title" content="Pennywise - Take Control of Your Money" />
	<meta
		property="og:description"
		content="Pennywise helps you track spending, stick to budgets, and reach savings goals faster. Beautiful insights, powerful features, bank-level security. Start your journey to financial wellness today."
	/>
	<meta property="og:site_name" content="Pennywise" />
	<meta property="og:image" content="https://pennywise.com/og.png" />

	<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:site" content="@site" />
	<meta name="twitter:creator" content="@pennywise" />
	<meta name="twitter:title" content="Pennywise - Take Control of Your Money" />
	<meta
		name="twitter:description"
		content="Pennywise helps you track spending, stick to budgets, and reach savings goals faster. Beautiful insights, powerful features, bank-level security. Start your journey to financial wellness today."
	/>
	<meta name="twitter:image" content="https://pennywise.com/og.png" />
</svelte:head>

<header>
	<h1 id="a11ty-headline" class="text-grey-900 text-4xl font-bold">Overview</h1>
</header>

<div class="p-8">
	<p>Dashboard content coming soon...</p>
</div>

// apps/web/app/(dashboard)/page.tsx
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Pennywise - Take Control of Your Money",
  description:
    "Pennywise helps you track spending, stick to budgets, and reach savings goals faster. Beautiful insights, powerful features, bank-level security. Start your journey to financial wellness today.",
  keywords:
    "personal finance, personal finance software, budget tracker, budget planner, expense tracking, track expenses, savings goals, financial planning, money management, budget app, spending tracker, financial wellness",

  openGraph: {
    type: "website",
    url: "https://pennywise.com",
    title: "Pennywise - Take Control of Your Money",
    description:
      "Pennywise helps you track spending, stick to budgets, and reach savings goals faster. Beautiful insights, powerful features, bank-level security. Start your journey to financial wellness today.",
    siteName: "Pennywise",
    images: "https://pennywise.com/og.png",
  },
  twitter: {
    card: "summary_large_image",
    site: "@site",
    creator: "@pennywise",
    title: "Pennywise - Take Control of Your Money",
    description:
      "Pennywise helps you track spending, stick to budgets, and reach savings goals faster. Beautiful insights, powerful features, bank-level security. Start your journey to financial wellness today.",
    images: "https://pennywise.com/og.png",
  },
  robots: "noindex, nofollow",
};

export default function Page() {
  return (
    <>
      <header>
        <h1 id="a11ty-headline" className="text-4xl font-bold text-grey-900">
          Overview
        </h1>
      </header>
    </>
  );
}
