// apps/site/src/routes/(dashboard)/budgets/+page.svelte
<script lang="ts">
</script>

<svelte:head>
	<title>Budgets - Pennywise</title>
	<meta name="description" content="Create and manage your budgets" />
	<meta name="robots" content="noindex, nofollow" />
</svelte:head>

<header>
	<h1 id="a11ty-headline" class="text-grey-900 text-4xl font-bold">Budgets</h1>
</header>

<div class="p-8">
	<p>Budgets content coming soon...</p>
</div>

// apps/web/src/routes/(dashboard)/budgets.tsx
import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/(dashboard)/budgets")({
  component: Page,
});

function Page() {
  return (
    <>
      <header>
        <h1 id="a11ty-headline" className="text-4xl font-bold text-grey-900">
          Budgets
        </h1>
      </header>
      <div className="p-8">
        <p>Budgets content coming soon...</p>
      </div>
    </>
  );
}
