// apps/site/src/routes/(auth)/signup/+page.svelte
<script lang="ts">
	import { signUpSchema } from '$lib/schema/auth';
	import { superForm } from 'sveltekit-superforms';
	import { zod } from 'sveltekit-superforms/adapters';

	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();

	const form = $derived.by(() =>
		superForm(data.form, {
			validators: zod(signUpSchema),
			taintedMessage: false
		})
	);

	const { form: formData, enhance, errors } = $derived(form);
</script>

<main class="bg-beige-100 flex min-h-screen w-full items-center justify-center px-4">
	<form
		action="?/signup"
		method="POST"
		use:enhance
		class={[
			'mx-auto flex w-full max-w-2xl flex-col gap-8',
			'rounded-xl bg-white px-8 py-12 shadow-md'
		]}
	>
		<h1 id="a11ty-headline" class="text-grey-900 text-4xl font-bold">Sign Up</h1>

		<div class="flex flex-col gap-4">
			<label for={$formData.name} class="flex flex-col gap-2">
				<span class="text-grey-900 text-sm font-semibold">Name</span>
				<input
					type="text"
					name="name"
					value={$formData.name}
					placeholder="John Doe"
					class={[
						'rounded border px-4 py-2',
						$errors.name ? 'border-red-500 bg-red-50' : 'border-grey-300 bg-white'
					]}
				/>
				{#if $errors.name}
					<span class="text-sm text-red-500">{$errors.name[0]}</span>
				{/if}
			</label>

			<label for={$formData.email} class="flex flex-col gap-2">
				<span class="text-grey-900 text-sm font-semibold">Email</span>
				<input
					type="email"
					name="email"
					value={$formData.email}
					placeholder="user@example.com"
					class={[
						'rounded border px-4 py-2',
						$errors.email ? 'border-red-500 bg-red-50' : 'border-grey-300 bg-white'
					]}
				/>
				{#if $errors.email}
					<span class="text-sm text-red-500">{$errors.email[0]}</span>
				{/if}
			</label>

			<label for={$formData.password} class="flex flex-col gap-2">
				<span class="text-grey-900 text-sm font-semibold">Password</span>
				<input
					type="password"
					name="password"
					value={$formData.password}
					placeholder="••••••••"
					class={[
						'rounded border px-4 py-2',
						$errors.password ? 'border-red-500 bg-red-50' : 'border-grey-300 bg-white'
					]}
				/>
				{#if $errors.password}
					<span class="text-sm text-red-500">{$errors.password[0]}</span>
				{/if}
			</label>
		</div>

		<button
			type="submit"
			class={[
				'bg-brand-500 rounded px-6 py-2 font-semibold text-white',
				'hover:bg-brand-600 transition-colors'
			]}
		>
			Create Account
		</button>

		<p class="text-grey-500 text-center text-sm">
			Already have an account?{' '}
			<a href="/auth/signin" class="text-brand-500 hover:text-brand-600 font-semibold"> Sign In </a>
		</p>
	</form>
</main>

// apps/site/src/routes/(auth)/signup.tsx
import { getFormProps, getInputProps, useForm } from "@conform-to/react";
import { getZodConstraint, parseWithZod } from "@conform-to/zod/v4";
import { Link, createFileRoute } from "@tanstack/react-router";
import { useActionState } from "react";

import { SignUpSchema as schema } from "@/schema/auth";
import { signup } from "@/server/auth";

export const Route = createFileRoute("/(auth)/signup")({
  component: Page,
});

function Page() {
  const [lastResult, action] = useActionState(signup, undefined);
  const [form, fields] = useForm({
    lastResult,
    constraint: getZodConstraint(schema),
    shouldValidate: "onBlur",
    shouldRevalidate: "onInput",
    onValidate({ formData }) {
      return parseWithZod(formData, { schema });
    },
  });

  return (
    <form
      action={action}
      {...getFormProps(form)}
      className="mx-auto flex w-full max-w-2xl flex-col gap-8 rounded-xl bg-white px-8 py-12 shadow-md"
    >
      <h1 id="a11ty-headline" className="text-4xl font-bold text-grey-900">
        Sign Up
      </h1>

      <div className="flex flex-col gap-4">
        <label htmlFor={fields.name.id} className="flex flex-col gap-2">
          <span className="text-sm font-semibold text-grey-900">Name</span>
          <input
            {...getInputProps(fields.name, { type: "text" })}
            placeholder="John Doe"
            className="rounded border border-grey-300 px-4 py-2"
          />
          {fields.name.errors && (
            <span className="text-sm text-red-500">{fields.name.errors[0]}</span>
          )}
        </label>

        <label htmlFor={fields.email.id} className="flex flex-col gap-2">
          <span className="text-sm font-semibold text-grey-900">Email</span>
          <input
            {...getInputProps(fields.email, { type: "email" })}
            placeholder="user@example.com"
            className="rounded border border-grey-300 px-4 py-2"
          />
          {fields.email.errors && (
            <span className="text-sm text-red-500">{fields.email.errors[0]}</span>
          )}
        </label>

        <label htmlFor={fields.password.id} className="flex flex-col gap-2">
          <span className="text-sm font-semibold text-grey-900">Password</span>
          <input
            {...getInputProps(fields.password, { type: "password" })}
            placeholder="••••••••"
            className="rounded border border-grey-300 px-4 py-2"
          />
          {fields.password.errors && (
            <span className="text-sm text-red-500">{fields.password.errors[0]}</span>
          )}
        </label>
      </div>

      <button
        type="submit"
        className="rounded bg-brand-500 px-6 py-2 font-semibold text-white hover:bg-brand-600"
      >
        Create Account
      </button>

      <p className="text-center text-sm text-grey-500">
        Already have an account?{" "}
        <Link to="/signin" className="font-semibold text-brand-500 hover:text-brand-600">
          Sign In
        </Link>
      </p>
    </form>
  );
}
