// apps/site/components/dialog.tsx
"use client";

import { tw } from "@/helpers/tailwind";
import { useRouter } from "next/navigation";
import { useEffect, useRef } from "react";

type Props = React.ComponentPropsWithRef<"dialog">;

export const Dialog = ({ className, children, ...attrs }: Props) => {
  const router = useRouter();

  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => {
    const dialog = ref.current;
    if (!dialog) return;
    if (!dialog.open) dialog.showModal();
    return () => {
      if (dialog.open) dialog.close();
    };
  }, []);

  return (
    <dialog
      closedby="any"
      aria-modal="true"
      {...attrs}
      onClose={() => router.back()}
      ref={ref}
      className={tw([
        "mx-4 my-auto max-w-xl rounded-xl bg-white p-8 shadow-xl backdrop:pointer-events-auto backdrop:bg-grey-900/50 sm:mx-auto",
        className,
      ])}
    >
      <section className="flex flex-col gap-6">{children}</section>
    </dialog>
  );
};

//  <dialog
//       ref={ref}
//       onClose={handleClose}
//       className={twMerge(
//         `
//         w-[90vw]
//         max-w-lg
//         max-h-[90vh]
//         overflow-hidden

//         rounded-xl
//         border
//         border-zinc-200
//         bg-white
//         p-0
//         shadow-xl

//         backdrop:bg-black/40

//         data-[state=closing]:animate-out
//         data-[state=closing]:fade-out
//         data-[state=closing]:zoom-out-95

//         motion-safe:animate-in
//         motion-safe:fade-in
//         motion-safe:zoom-in-95
//         `,
//         className
//       )}
//     >
//       {children}
//     </dialog>

// src/components/dialog.svelte
<script lang="ts">
	import type { HTMLDialogAttributes } from 'svelte/elements';

	type Props = HTMLDialogAttributes;

	let { open = $bindable(false), children, ...attrs }: Props = $props();

	let dialog: HTMLDialogElement | null = $state(null);

	$effect(() => {
		if (!dialog) return;
		if (open && !dialog.open) dialog.showModal();
		if (!open && dialog.open) dialog.close();
	});
</script>

<dialog
	bind:this={dialog}
	aria-modal="true"
	closedby="any"
	{...attrs}
	class={[
		'm-auto w-full max-w-xl rounded-xl bg-white p-8 shadow-xl',
		'scale-95 opacity-0 backdrop:bg-grey-900/50',
		'transition transition-discrete duration-200 ease-in',
		'open:scale-100 open:opacity-100 starting:open:scale-95 starting:open:opacity-0'
	]}
>
	<section class="flex flex-col gap-6">
		{@render children?.()}
	</section>
</dialog>
