// apps/site/src/routes/(dashboard)/pots.tsx
import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/(dashboard)/pots")({
  component: Page,
});

function Page() {
  return (
    <>
      <header>
        <h1 id="a11ty-headline" className="text-4xl font-bold text-grey-900">
          Pots
        </h1>
      </header>
      <div className="p-8">
        <p>Pots content coming soon...</p>
      </div>
    </>
  );
}

// apps/site/src/routes/(dashboard)/pots/+page.svelte
<script lang="ts">
</script>

<svelte:head>
	<title>Pots - Pennywise</title>
	<meta name="description" content="Manage your savings pots" />
	<meta name="robots" content="noindex, nofollow" />
</svelte:head>

<header>
	<h1 id="a11ty-headline" class="text-grey-900 text-4xl font-bold">Pots</h1>
</header>

<div class="p-8">
	<p>Pots content coming soon...</p>
</div>
