// apps/site/src/routes/(dashboard)/transactions/+page.svelte
<script lang="ts">
</script>

<svelte:head>
	<title>Transactions - Pennywise</title>
	<meta name="description" content="View and manage your transactions" />
	<meta name="robots" content="noindex, nofollow" />
</svelte:head>

<header>
	<h1 id="a11ty-headline" class="text-grey-900 text-4xl font-bold">Transactions</h1>
</header>

<div class="p-8">
	<p>Transactions content coming soon...</p>
</div>

// apps/site/src/routes/(dashboard)/transactions.tsx
import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/(dashboard)/transactions")({
  component: Page,
});

function Page() {
  return (
    <>
      <header>
        <h1 id="a11ty-headline" className="text-4xl font-bold text-grey-900">
          Transactions
        </h1>
      </header>
      <div className="p-8">
        <p>Transactions content coming soon...</p>
      </div>
    </>
  );
}
